---
title: "Alpha diversity~outcome"
author: "Michael Conroy"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.align = "center",
                      fig.width = 10,
                      fig.height = 7)

setwd("S:/MolecularOncology/Users/Michael C/neoadjuvant microbiome/NGS results/microbiome_R_directory")
```

```{r load_packages, include=FALSE}
library(ggplot2) 
library(tidyr) 
library(dplyr) 
library(readxl) 
library(ggpubr)
library(rstatix)
library(tidyverse)
library(survival)
library(broom)
library(knitr)
library(openxlsx)
```

## The association between alpha diversity and outcomes

Exploring the association between baseline alpha diversity and outcomes.

```{r reading data}
first_specs <- read_excel("first_specimens_only.xlsx")
first_specs$MPR <- as.factor(first_specs$MPR)
first_specs$alive_NED_24mo <- as.factor(first_specs$alive_NED_24mo)
first_specs$prognostic_group <- as.factor(first_specs$prognostic_group)
first_specs$recurrence <- 1 - first_specs$recurrence_free
first_specs$recurrence_free <- NULL
first_specs$death <- 1 - first_specs$alive
first_specs$alive <- NULL
first_specs <- first_specs %>%
  dplyr::filter(!is.na(rad_response_preop))

first_specs$rad_response_preop <- as.factor(first_specs$rad_response_preop)
names(first_specs)[names(first_specs) == "rad_response_preop"] <- "orr"
# Recode 0 and 2 as "response absent", and 1 as "response present"
first_specs$orr <- ifelse(first_specs$orr == 1,
                          "response present",
                          ifelse(first_specs$orr %in% c(0, 2),
                                 "response absent",
                                 NA))   # keep other values as NA

# Then convert to factor with desired level order
first_specs$orr <- factor(first_specs$orr,
                          levels = c("response absent", "response present"))
```

## Alpha diversity and MPR status


```{r statistical testing,include=FALSE}

# testing for normality of distribution

shapiro.test(first_specs$simpson_reciprocal)

shapiro.test(first_specs$simpson_reciprocal[first_specs$prognostic_group == 1])
shapiro.test(first_specs$simpson_reciprocal[first_specs$prognostic_group == 2])
shapiro.test(first_specs$simpson_reciprocal[first_specs$prognostic_group == 3])

# testing for significant difference between groups

t_test_simpson <- t.test(simpson_reciprocal~MPR,data=first_specs)
p_simpson <- t_test_simpson$p.value

t_test_shannon <- t.test(shannon~MPR,data=first_specs)
p_shannon <- t_test_shannon$p.value

t_test_chao <- t.test(chao1~MPR,data=first_specs)
p_chao <- t_test_chao$p.value

anova_simpson_prognostic <- aov(simpson_reciprocal ~ prognostic_group, data = first_specs)
anova_summary <- summary(anova_simpson_prognostic)
p_prognostic_simpson <- anova_summary[[1]][["Pr(>F)"]][1]

```

```{r medians, echo=FALSE}

MPR_1_set <- first_specs %>% filter(MPR == "1")
MPR_0_set <- first_specs %>% filter(MPR == "0")

median_simpson_MPR_1 <- median(MPR_1_set$simpson_reciprocal, na.rm=TRUE)
median_simpson_MPR_0 <- median(MPR_0_set$simpson_reciprocal, na.rm=TRUE)
median_simpson_overall <- median(first_specs$simpson_reciprocal, na.rm=TRUE)

range_simpson_MPR_1 <- range(MPR_1_set$simpson_reciprocal)
range_simpson_MPR_0 <- range(MPR_0_set$simpson_reciprocal)

```


```{r graph_simpson}

simpson_plot <- ggplot(first_specs, aes(x = MPR, y = simpson_reciprocal, fill = MPR)) + geom_boxplot() + geom_jitter(position = position_jitter(width = 0.3), size = 2, alpha = 0.5) + labs(x = "MPR", y = "Inverse Simpson", fill = "MPR") + theme_minimal() + theme(axis.title.x = element_text(margin = margin(t = 20), size = 14),axis.title.y = element_text(size = 14)) + theme(
  axis.line = element_line(color = "black", linewidth = 0.5)
)

simpson_plot_p <- simpson_plot + annotate("text", x=1.5, y = 30, label = paste("[ p =", round(p_simpson, 4), "]", sep = ""), 
                  vjust = -1, size = 4)

print(simpson_plot_p)

ggsave("simpson_plot_p.pdf", plot = simpson_plot_p, device = "pdf", width = 8, height = 6)

```


```{r graph_shannon}

shannon_plot <- ggplot(first_specs, aes(x = MPR, y = shannon, fill = MPR)) + geom_boxplot() + geom_jitter(position = position_jitter(width = 0.3), size = 2, alpha = 0.5) + labs(x = "MPR", y = "shannon", fill = "MPR") + theme_minimal() + theme(axis.title.x = element_text(margin = margin(t = 20), size = 14),axis.title.y = element_text(size = 14)) + theme(
  axis.line = element_line(color = "black", linewidth = 0.5)
)

shannon_plot_p <- shannon_plot + annotate("text", x=1.5, y = 8, label = paste("[ p =", round(p_shannon, 4), "]", sep = ""), 
                  vjust = -1, size = 4)

print(shannon_plot_p)

ggsave("shannon_plot_p.pdf", plot = shannon_plot_p, device = "pdf", width = 8, height = 6)

```

```{r graph_chao}

chao_plot <- ggplot(first_specs, aes(x = MPR, y = chao1, fill = MPR)) + geom_boxplot() + geom_jitter(position = position_jitter(width = 0.3), size = 2, alpha = 0.5) + labs(x = "MPR", y = "chao", fill = "MPR") + theme_minimal() + theme(axis.title.x = element_text(margin = margin(t = 20), size = 14),axis.title.y = element_text(size = 14)) + theme(
  axis.line = element_line(color = "black", linewidth = 0.5)
)

chao_plot_p <- chao_plot + annotate("text", x=1.5, y = 100, label = paste("[ p =", round(p_chao, 4), "]", sep = ""), 
                  vjust = -1, size = 4)

print(chao_plot_p)

ggsave("chao_plot_p.pdf", plot = chao_plot_p, device = "pdf", width = 8, height = 6)


```


## Alpha diversity and RFS at 2 years

```{r RFS_graph, include=FALSE}

ggplot(first_specs, aes(x = alive_NED_24mo, y = simpson_reciprocal, fill = alive_NED_24mo)) + geom_boxplot() + geom_jitter(position = position_jitter(width = 0.3), size = 2, alpha = 0.5) + labs(x = "Recurrence-free at 24 months", y = "Inverse Simpson", fill = "MPR") + theme_minimal() + theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

```{r statistical_testing_RFS,include=FALSE}

# testing for significant difference between groups

t_test_24mo <- t.test(simpson_reciprocal~alive_NED_24mo,data=first_specs)
p_24mo <- t_test_24mo$p.value

```

```{r graph_24}

RFS_plot <- ggplot(first_specs, aes(x = alive_NED_24mo, y = simpson_reciprocal, fill = alive_NED_24mo)) + geom_boxplot() + geom_jitter(position = position_jitter(width = 0.3), size = 2, alpha = 0.5) + labs(x = "Recurrence-free at 24 months", y = "Inverse Simpson", fill = "MPR") + theme_minimal() + theme(
  axis.line = element_line(color = "black", linewidth = 0.5)
)

RFS_plot_p <- RFS_plot + annotate("text", x=1.5, y = 30, label = paste("[ p =", round(p_24mo, 4), "]", sep = ""), 
                  vjust = -1, size = 4)

print(RFS_plot_p)

```

```{r prognostic_graph_simpson}

prognostic_simpson <- ggplot(first_specs, aes(x = prognostic_group, y = simpson_reciprocal, fill = prognostic_group)) + geom_boxplot() + geom_jitter(position = position_jitter(width = 0.3), size = 2, alpha = 0.5) + labs(x = "Prognostic grouping", y = "Inverse Simpson", fill = "Prognostic Grouping") + theme_minimal() + theme(axis.title.x = element_text(margin = margin(t = 20), size = 14),axis.title.y = element_text(size = 14)) + theme(
  axis.line = element_line(color = "black", linewidth = 0.5)
)

prognostic_simpson_p <- prognostic_simpson + annotate("text", x=1.5, y = 30, label = paste("[ p =", round(p_prognostic_simpson, 4), "]", sep = ""), 
                  vjust = -1, size = 4)

print(prognostic_simpson_p)

```

```{r }

# similar to above codechunk but with explanatory labels in legend for the three groupings.

prognostic_simpson <- ggplot(first_specs, aes(x = prognostic_group, y = simpson_reciprocal, fill = prognostic_group)) +
  geom_boxplot() + 
  geom_jitter(position = position_jitter(width = 0.3), size = 2, alpha = 0.5) + 
  labs(x = "Prognostic grouping", y = "Inverse Simpson", fill = "Prognostic Grouping") +
  scale_fill_manual(values = c("1" = "#F8766D", "2" = "#00BA38", "3" = "#619CFF"),
                    labels = c("1" = "no recurrence", "2" = "delayed recurrence", "3" = "early recurrence")) +
  theme_minimal() + 
  theme(axis.title.x = element_text(margin = margin(t = 20), size = 14),
        axis.title.y = element_text(size = 14),
        axis.line = element_line(color = "black", linewidth = 0.5))

prognostic_simpson_p <- prognostic_simpson + annotate("text", x = 1.5, y = 30, label = paste("[ p =", round(p_prognostic_simpson, 4), "]", sep = ""), 
                                                      vjust = -1, size = 4)

ggsave("prognostic_simpson_plot.pdf", plot = prognostic_simpson_p, device = "pdf", width = 8, height = 6)

```

```{r alpha diversity overall survival cph}

library(survival)

cox_model <- coxph(Surv(OS, death) ~ simpson_reciprocal, data = first_specs)
summary(cox_model)


```

```{r alpha diversity RFS  cph}

cox_model <- coxph(Surv(PFS, death_recurrence) ~ simpson_reciprocal, data = first_specs)
summary(cox_model)


```
```{r alpha with OS and RFS}

# Fit both models
cox_OS  <- coxph(Surv(OS, death) ~ simpson_reciprocal, data = first_specs)
cox_PFS <- coxph(Surv(PFS, death_recurrence) ~ simpson_reciprocal, data = first_specs)

# Extract results
tbl_OS <- tidy(cox_OS, exponentiate = TRUE, conf.int = TRUE) %>%
  mutate(Model = "Overall Survival")
tbl_PFS <- tidy(cox_PFS, exponentiate = TRUE, conf.int = TRUE) %>%
  mutate(Model = "Progression-Free Survival")

# Combine and format
cox_table <- bind_rows(tbl_OS, tbl_PFS) %>%
  transmute(
    Model,
    Variable = term,
    HR_CI = sprintf("%.2f (%.2f–%.2f)", estimate, conf.low, conf.high),
    p.value = signif(p.value, 3)
  )

# Display in console
kable(cox_table, caption = "Cox proportional hazards models for OS and PFS")

# Save to Excel (optional)
write.xlsx(cox_table, "alpha_cox_RFS_OS.xlsx")

```


## Alpha diversity and RR status


```{r statistical testing,include=FALSE}


# testing for significant difference between groups

t_test_simpson <- t.test(simpson_reciprocal~orr,data=first_specs)
p_simpson <- t_test_simpson$p.value

t_test_shannon <- t.test(shannon~orr,data=first_specs)
p_shannon <- t_test_shannon$p.value

t_test_chao <- t.test(chao1~orr,data=first_specs)
p_chao <- t_test_chao$p.value

```

```{r medians, echo=FALSE}

orr_1_set <- first_specs %>% filter(orr == "1")
orr_0_set <- first_specs %>% filter(orr == "0")

median_simpson_orr_1 <- median(orr_1_set$simpson_reciprocal, na.rm=TRUE)
median_simpson_orr_0 <- median(orr_0_set$simpson_reciprocal, na.rm=TRUE)
median_simpson_overall <- median(first_specs$simpson_reciprocal, na.rm=TRUE)

range_simpson_orr_1 <- range(orr_1_set$simpson_reciprocal)
range_simpson_orr_0 <- range(orr_0_set$simpson_reciprocal)

```


```{r graph_simpson}

simpson_plot <- ggplot(first_specs, aes(x = orr, y = simpson_reciprocal, fill = orr)) + geom_boxplot() + geom_jitter(position = position_jitter(width = 0.3), size = 2, alpha = 0.5) + labs(x = "Response Rate", y = "Inverse Simpson", fill = "Radiographic Response") + theme_minimal() + theme(axis.title.x = element_text(margin = margin(t = 20), size = 14),axis.title.y = element_text(size = 14)) + theme(
  axis.line = element_line(color = "black", linewidth = 0.5)
)

simpson_plot_p <- simpson_plot + annotate("text", x=1.5, y = 30, label = paste("[ p =", round(p_simpson, 4), "]", sep = ""), 
                  vjust = -1, size = 4)

print(simpson_plot_p)

ggsave("simpson_plot_orr.pdf", plot = simpson_plot_p, device = "pdf", width = 8, height = 6)

```
